import React from 'react'

import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Auco Tech Test - By Juan Hurtado',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang='en'>
      <body className='m-0 box-border flex items-center bg-gradient-to-b from-sky-600 to-indigo-600'>
        <main className='w-full flex-col px-12 items-center'>
          <header className=' m-8 text-center font-sans'>
            <h1 className='text-2xl sm:text-4xl md:text-5xl text-white font-bold'>Auco Technical Test Solution</h1>
            <h2 className='text-1xl sm:text-3x md:text-4xl text-white font-semibold'>Frontend Junior Developer - By Juan Hurtado 🚀</h2>
          </header>
          <main className='w-full items-center p-5 bg-slate-100'>
            {children}
          </main>
        </main>
      </body>
    </html>
  )
}
