import React from 'react'

import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Auco Tech Test - By Juan Hurtado',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='flex items-center bg-gradient-to-b from-sky-600 to-indigo-600'>
        {children}
      </body>
    </html>
  )
}
